[package]
name = "tsukuyomi-core"
version = "0.1.0"
edition = "2024"

[dependencies]
artnet_protocol="0.4.3"
itertools = "0.14.0"
quick-xml = {version="0.38.3", features=["serialize"]}
serde = {version="1.0.228", features=["derive"]}
