[package]
name = "tsukuyomi-slint"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = { path = "../../slint/api/rs/slint",features = ["backend-winit"] }
tsukuyomi-core={ path="../core" }
i-slint-backend-winit={ path = "../../slint/internal/backends/winit" }
uuid={workspace=true}
tracing={workspace=true}
tracing-subscriber="0.3.0"

[build-dependencies]
slint-build = { path="../../slint/api/rs/build" }
