name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout main repo
      uses: actions/checkout@v4
      with: 
        path: tsukuyomi-rs
    - name: checkout slint repo
      uses: actions/checkout@v4
      with:
        repository: taichi765/slint
        path: slint
    - name: Build
      working-directory: tsukuyomi-rs
      run: cargo build --verbose
    - name: Run tests
      working-directory: tsukuyomi-rs
      run: cargo test --verbose
